<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHVbuuhc\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHVbuuhc/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHVbuuhc.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHVbuuhc\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerHVbuuhc\App_KernelDevDebugContainer([
    'container.build_hash' => 'HVbuuhc',
    'container.build_id' => 'efde0d51',
    'container.build_time' => 1674158962,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHVbuuhc');
